site_name: Documentation
docs_dir: docs
pages:
  - Welcome: index.md
  - Delayed Execution: delayed-exec.md
  - Real-Time Signalling: realtime-signalling.md
  - Services: services.md
  - Key/Value Storage: kvstore.md
markdown_extensions:
    - admonition
