
<div class="panel hazaar stats">
    <div class="panel-header">Server Status</div>
    <div class="panel-content">
        <div class="item wide">
            <div class="item-content">
                <div class="item-label">Uptime</div>
                <div class="item-value" id="uptime" data-start="0"></div>
            </div>
        </div>

        <div class="item wide">
            <div class="item-content">
                <div class="item-label">PID</div>
                <div class="item-value" id="status-pid"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Memory (MB)</div>
                <div class="item-value"
                     id="status-memory"></div>

            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Sockets</div>
                <div class="item-value" id="status-connections"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Clients</div>
                <div class="item-value" id="status-clients"></div>
            </div>
        </div>

        <div class="item-header">
            Jobs
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Processed</div>
                <div class="item-value" id="status-processed"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Completed</div>
                <div class="item-value" id="status-execs"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Late</div>
                <div class="item-value" id="status-lateExecs"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Failed</div>
                <div class="item-value" id="status-failed"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Busy</div>
                <div class="item-value" id="status-processes"></div>
            </div>
        </div>

        <div class="item">
            <div class="item-content">
                <div class="item-label">Retries</div>
                <div class="item-value" id="status-retries"></div>
            </div>
        </div>
        <div class="item">
            <div class="item-content">
                <div class="item-label">Queue</div>
                <div class="item-value" id="status-queue"></div>
            </div>
        </div>
        <div class="item">
            <div class="item-content">
                <div class="item-label">Process Limits</div>
                <div class="item-value" id="status-limitHits"></div>
            </div>
        </div>

        <div class="item-header">
            Signalling
        </div>
        <div class="item">
            <div class="item-content">
                <div class="item-label">Subscriptions</div>
                <div class="item-value"
                     id="status-subscriptions"></div>
            </div>
        </div>
        <div class="item">
            <div class="item-content">
                <div class="item-label">Events</div>
                <div class="item-value" id="status-events"></div>
            </div>
        </div>
    </div>
</div>